### ISSUE TITLE
Assets requested from CSS do not have a long cache time

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-coronavirus-vulnerable-people-form#136]
URL | Cache TTL | Size
-- | -- | --
/assets/light-94a07e06a1-v2-eedfb3c….woff2 | None | 50 KB
/assets/bold-b542beb274-v2-06eba01….woff2 | None | 31 KB
/assets/govuk-crest-2x-c654888….png | None | 9 KB
/assets/application-5dfb935….js | 1 d | 164 KB
/assets/application-7151bdd….css | 1 d | 26 KB
/assets/print-639d73a….css | 1 d | 3 KB

We should:

- see if it's possible to cache all assets not just css
- increase the cache time from 1d to something longer

This'll mean that there's no risk of users re-downloading the font between page transitions, which would make the page loads significantly slower.

- https://web.dev/uses-long-cache-ttl/#how-to-cache-static-resources-using-http-caching

**Comment by NickColley** [comment]
cc @Nooshu

**Comment by Nooshu** [comment]
Strange, that's something I checked. I can see the same `Cache-Control` headers on the CSS / JS as the fonts and the crest image:

![Screenshot 2020-03-22 at 23 37 42](https://user-images.githubusercontent.com/1223960/77266062-58dd1700-6c96-11ea-89c9-4818a623f2cc.png)
![Screenshot 2020-03-22 at 23 37 57](https://user-images.githubusercontent.com/1223960/77266068-5bd80780-6c96-11ea-9b16-7b70212fd09c.png)

Agreed, upping the caching to `31536000` is a quick fix. No reason not too since we add a  hash to the filenames anyway, so will be invalidated if changed. This is also a recommendation from WebPageTest:

![Screenshot 2020-03-22 at 23 47 46](https://user-images.githubusercontent.com/1223960/77266849-a0fd3900-6c98-11ea-8787-61c837becd81.png)

**Comment by theseanything** [comment]
Think these should be fine? - rails in production mode should be setting the cache header https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form/blob/839fce2da57e7a97a2fd7b75b880980dc5e9fffa/config/environments/production.rb#L33

(But that might just be the public assets?)

**Comment by NickColley** [comment]
Wonder why it's being reported as not having a cache limit then hmm
